export default [
  {
    title:'首页',
    key:'/admin/home'
  },
  {
    title:'UI',
    key:'/admin/ui',
    children:[
      {
        title:'按钮',
        key:'/admin/ui/buttons'
      },
      {
        title:'弹窗',
        key:'/admin/ui/modals'
      },
      {
        title:'Loading',
        key:'/admin/ui/loadings'
      },
      {
        title:'Notification',
        key:'/admin/ui/notifications'
      },
      {
        title:'Message',
        key:'/admin/ui/meaasges'
      },
      {
        title:'Tabs',
        key:'/admin/ui/tabs'
      },
      {
        title:'Carousel',
        key:'/admin/ui/carousel'
      }
    ]
  },
  {
    title:'表单',
    key:'/admin/from',
    children:[
      {
        title:'Logins',
        key:'/admin/form/logins'
      }
    ]
  },
  {
    title:'表格',
    key:'/admin/table',
    children:[
     
    ]
  },
  {
    title:'富文本',
    key:'/admin/ueditor'
  },
  {
    title:'城市管理',
    key:'/admin/ueditor1'
  },
  {
    title:'订单管理',
    key:'/admin/ueditor2'
  },
  {
    title:'员工管理',
    key:'/admin/ueditor3'
  },
  {
    title:'车辆地图',
    key:'/admin/ueditor4'
  },
  {
    title:'图标',
    key:'/admin/icons',
    children:[

    ]
  },
  {
    title:'设置权限',
    key:'/admin/icons1',
  }
]